# Generated by Django 6.0.4 on 2026-04-23 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KieuGiai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_file', models.CharField(max_length=255)),
                ('kich_thuoc', models.BigIntegerField()),
                ('ma_bam', models.CharField(max_length=128)),
                ('drive_file_id', models.CharField(max_length=100)),
                ('ngay_tai_len', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
