# Generated by Django 6.0.4 on 2026-05-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
